name: Our very first GitHub Action
on: workflow_dispatch
jobs: 
	Testing-Actions:
		runs-on: ubuntu-latest
		steps:
			- run: echo "I'm walking! ğŸš¶â€â™€ï¸"
			- run: echo "Actually, I\'m running on ${{ runner.os }} ğŸƒ"
			- run: echo "I'm done! My status: ${{ job.status }} ğŸ‰"
