name: Our very first GitHub Action
on: workflow_dispatch
jobs:
  Testing-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: A action is born
        run: |
          echo "I'm walking! ğŸš¶â€â™€ï¸"
          echo "Actually, I'm running on ${{ runner.os }} ğŸƒ"
          echo "I'm done! My status: ${{ job.status }} ğŸ‰"
